//! Phase 4's reporting-only absolute-accuracy comparison.
//!
//! The reference fixture is generated by `tools/generate_rys_high_precision_reference.py`
//! with mpmath at 100 decimal digits.  It is deliberately outside shipped crates and
//! timed kernels: libcint parity remains the compatibility verdict.

use anyhow::{Context, Result, bail};
use cintx_cubecl::math::rys::rys_roots_host;
use serde_json::Value;
use std::fs;
use std::path::Path;

pub const DEFAULT_REFERENCE_PATH: &str = "artifacts/rys_high_precision_reference.json";

#[derive(Debug)]
struct ReferenceCase {
    nroots: usize,
    x: f64,
    roots: Vec<f64>,
    weights: Vec<f64>,
    boys: Vec<f64>,
}

pub fn run_rys_absolute_accuracy(reference_path: &Path) -> Result<()> {
    let cases = load_reference(reference_path)?;
    if cases.is_empty() {
        bail!("high-precision Rys reference has no cases");
    }

    let mut markdown = String::from(
        "# Rys Absolute Accuracy Report (2026-08-30)\n\n\
         This reporting-only comparison uses a 100-decimal-digit mpmath Gauss rule\n\
         generated from the defining Boys moments. It does not alter libcint parity\n\
         gates or tolerance policy.\n\n\
         | nroots | x regime | vendor max abs | cintx max abs | cintx-vendor max abs | \
         vendor Boys max abs | cintx Boys max abs |\n\
         |---:|---:|---:|---:|---:|---:|---:|\n",
    );
    let mut worst_vendor = 0.0_f64;
    let mut worst_cintx = 0.0_f64;
    let mut worst_delta = 0.0_f64;

    for case in &cases {
        let (vendor_roots, vendor_weights) = vendor_roots(case.nroots, case.x)?;
        let (cintx_roots, cintx_weights) = rys_roots_host::<f64>(case.nroots, case.x);
        ensure_len("vendor roots", case, &vendor_roots)?;
        ensure_len("vendor weights", case, &vendor_weights)?;
        ensure_len("cintx roots", case, &cintx_roots)?;
        ensure_len("cintx weights", case, &cintx_weights)?;

        let vendor_error =
            max_error(&vendor_roots, &case.roots).max(max_error(&vendor_weights, &case.weights));
        let cintx_error =
            max_error(&cintx_roots, &case.roots).max(max_error(&cintx_weights, &case.weights));
        let delta =
            max_error(&cintx_roots, &vendor_roots).max(max_error(&cintx_weights, &vendor_weights));
        let vendor_boys_error = max_error(
            &boys_from_rule(&vendor_roots, &vendor_weights, case.boys.len()),
            &case.boys,
        );
        let cintx_boys_error = max_error(
            &boys_from_rule(&cintx_roots, &cintx_weights, case.boys.len()),
            &case.boys,
        );

        worst_vendor = worst_vendor.max(vendor_error);
        worst_cintx = worst_cintx.max(cintx_error);
        worst_delta = worst_delta.max(delta);
        markdown.push_str(&format!(
            "| {} | {:.6e} | {:.3e} | {:.3e} | {:.3e} | {:.3e} | {:.3e} |\n",
            case.nroots,
            case.x,
            vendor_error,
            cintx_error,
            delta,
            vendor_boys_error,
            cintx_boys_error
        ));
    }
    markdown.push_str(&format!(
        "\nWorst absolute errors: vendor `{worst_vendor:.3e}`, cintx `{worst_cintx:.3e}`, \
         cintx-vendor delta `{worst_delta:.3e}`.\n"
    ));

    for destination in [
        "artifacts/rys_absolute_accuracy_2026-08-30.md",
        "/tmp/cintx_artifacts/rys_absolute_accuracy_2026-08-30.md",
    ] {
        let path = Path::new(destination);
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)
                .with_context(|| format!("creating report directory {}", parent.display()))?;
        }
        fs::write(path, &markdown)
            .with_context(|| format!("writing Rys accuracy report {}", path.display()))?;
        println!("Emitted Rys absolute-accuracy report to: {destination}");
    }
    Ok(())
}

#[cfg(has_vendor_libcint)]
fn vendor_roots(nroots: usize, x: f64) -> Result<(Vec<f64>, Vec<f64>)> {
    Ok(cintx_oracle::vendor_ffi::vendor_CINTrys_roots(
        nroots as i32,
        x,
    ))
}

#[cfg(not(has_vendor_libcint))]
fn vendor_roots(_nroots: usize, _x: f64) -> Result<(Vec<f64>, Vec<f64>)> {
    bail!(
        "rys-absolute-accuracy requires CINTX_ORACLE_BUILD_VENDOR=1 so it can measure the vendored build"
    )
}

fn ensure_len(name: &str, case: &ReferenceCase, values: &[f64]) -> Result<()> {
    if values.len() != case.nroots {
        bail!(
            "{name} length {} != nroots {} at x={}",
            values.len(),
            case.nroots,
            case.x
        );
    }
    Ok(())
}

fn max_error(values: &[f64], reference: &[f64]) -> f64 {
    values
        .iter()
        .zip(reference)
        .map(|(value, expected)| (value - expected).abs())
        .fold(0.0, f64::max)
}

fn boys_from_rule(roots: &[f64], weights: &[f64], count: usize) -> Vec<f64> {
    (0..count)
        .map(|m| {
            roots
                .iter()
                .zip(weights)
                .map(|(root, weight)| weight * (root / (1.0 + root)).powi(m as i32))
                .sum()
        })
        .collect()
}

fn load_reference(path: &Path) -> Result<Vec<ReferenceCase>> {
    let source = fs::read_to_string(path)
        .with_context(|| format!("reading high-precision reference {}", path.display()))?;
    let json: Value = serde_json::from_str(&source)
        .with_context(|| format!("parsing high-precision reference {}", path.display()))?;
    let precision = json
        .get("precision_decimal_digits")
        .and_then(Value::as_u64)
        .context("reference is missing precision_decimal_digits")?;
    if precision < 80 {
        bail!("reference precision {precision} is below the required 80 decimal digits");
    }
    json.get("cases")
        .and_then(Value::as_array)
        .context("reference is missing cases array")?
        .iter()
        .map(|entry| {
            let nroots = entry
                .get("nroots")
                .and_then(Value::as_u64)
                .context("reference case is missing nroots")? as usize;
            let x = number(entry, "x")?;
            let roots = numbers(entry, "roots")?;
            let weights = numbers(entry, "weights")?;
            let boys = numbers(entry, "boys")?;
            if roots.len() != nroots || weights.len() != nroots || boys.len() != nroots * 2 {
                bail!("malformed reference case nroots={nroots} x={x}");
            }
            Ok(ReferenceCase {
                nroots,
                x,
                roots,
                weights,
                boys,
            })
        })
        .collect()
}

fn number(entry: &Value, field: &str) -> Result<f64> {
    entry
        .get(field)
        .and_then(Value::as_str)
        .context(format!("reference case is missing string {field}"))?
        .parse::<f64>()
        .with_context(|| format!("parsing reference {field}"))
}

fn numbers(entry: &Value, field: &str) -> Result<Vec<f64>> {
    entry
        .get(field)
        .and_then(Value::as_array)
        .context(format!("reference case is missing {field} array"))?
        .iter()
        .map(|value| {
            value
                .as_str()
                .context(format!("reference {field} value is not a string"))?
                .parse::<f64>()
                .with_context(|| format!("parsing reference {field} value"))
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::boys_from_rule;

    #[test]
    fn quadrature_boys_moments_use_rys_coordinate_not_u_directly() {
        let moments = boys_from_rule(&[1.0], &[2.0], 3);
        assert_eq!(moments, vec![2.0, 1.0, 0.5]);
    }
}
